package com.example.mercado.common.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {

    //COURSE
    COURSE_NOT_FOUND(HttpStatus.NOT_FOUND),
    COURSE_ALREADY_EXIST(HttpStatus.CONFLICT),
    COURSE_ALREADY_ARCHIVED(HttpStatus.BAD_REQUEST),
    COURSE_ALREADY_PUBLISHED(HttpStatus.BAD_REQUEST),
    COURSE_NAME_INVALID(HttpStatus.CONFLICT),

    //COURSE REQUIREMENT
    REQUIREMENT_ALREADY_EXIST(HttpStatus.CONFLICT),
    REQUIREMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    REQUIREMENT_POSITION_INVALID(HttpStatus.BAD_REQUEST),
    REQUIREMENT_SAME_TEXT(HttpStatus.BAD_REQUEST),
    REQUIREMENT_LIMIT_REACHED(HttpStatus.BAD_REQUEST),

    //COURSE LEARNING POINT
    LEARNING_POINT_ALREADY_EXIST(HttpStatus.CONFLICT),
    LEARNING_POINT_SAME_TEXT(HttpStatus.BAD_REQUEST),
    LEARNING_POINT_LIMIT_REACHED(HttpStatus.BAD_REQUEST),
    LEARNING_POINT_NOT_FOUND(HttpStatus.NOT_FOUND),
    LEARNING_POINT_POSITION_INVALID(HttpStatus.BAD_REQUEST),

    //LESSON
    LESSON_ALREADY_EXIST(HttpStatus.CONFLICT),
    LESSON_NOT_FOUND(HttpStatus.NOT_FOUND),
    LESSON_STATUS_INVALID(HttpStatus.BAD_REQUEST),

    //LESSON CONTENT
    LESSON_CONTENT_ALREADY_EXIST(HttpStatus.CONFLICT),
    LESSON_CONTENT_NOT_FOUND(HttpStatus.NOT_FOUND),

    //MODULE
    MODULE_ALREADY_ARCHIVED(HttpStatus.CONFLICT),
    MODULE_ALREADY_PUBLISHED(HttpStatus.BAD_REQUEST),
    MODULE_NOT_FOUND(HttpStatus.NOT_FOUND),
    MODULE_POSITION_INVALID(HttpStatus.BAD_REQUEST),
    MODULE_ALREADY_DELETED(HttpStatus.CONFLICT),
    MODULE_ALREADY_EXIST(HttpStatus.CONFLICT),

    //MODULE CONTENT
    MODULE_CONTENT_ALREADY_EXIST(HttpStatus.CONFLICT),
    MODULE_CONTENT_NOT_FOUND(HttpStatus.NOT_FOUND),

    //ASSIGNMENT
    ASSIGNMENT_ALREADY_EXIST(HttpStatus.CONFLICT),
    ASSIGNMENT_NOT_FOUND(HttpStatus.NOT_FOUND),

    //USER
    INVALID_USER_ROLE(HttpStatus.BAD_REQUEST),
    USER_ALREADY_EXIST(HttpStatus.CONFLICT),
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    USER_INACTIVATE(HttpStatus.FORBIDDEN),

    //MAIL
    MAIL_SEND_FAILED(HttpStatus.CONFLICT);

    private final HttpStatus code;

    ErrorCode(HttpStatus httpStatus) {
        this.code = httpStatus;
    }

    public HttpStatus getCode() {
        return code;
    }
}
