spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  mail:
    host: localhost
    port: 25
    username: test
    password: test
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false