CREATE TABLE achievement_table (
   active boolean,
   points integer,
   created_at timestamp(6) without time zone,
   enrolled_at timestamp(6) without time zone,
   id bigint NOT NULL,
   description character varying(255),
   icon_url character varying(255),
   name character varying(255),
   type character varying(255),
   CONSTRAINT achievement_table_type_check CHECK (((type)::text = ANY ((ARRAY['MODULE'::character varying, 'LESSONS'::character varying, 'COURSE'::character varying, 'CUSTOM'::character varying])::text[])))
);

ALTER TABLE achievement_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME achievement_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE assignments_table (
   max_score integer,
   "position" integer,
   created_at timestamp(6) without time zone NOT NULL,
   id bigint NOT NULL,
   lesson_id bigint,
   updated_at timestamp(6) without time zone,
   description character varying(1000),
   name character varying(255),
   status character varying(255),
   type character varying(255),
   CONSTRAINT assignments_table_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_ASSIGNED'::character varying, 'ASSIGNED'::character varying, 'SUBMITTED'::character varying, 'GRADED'::character varying, 'OVERDUE'::character varying])::text[]))),
   CONSTRAINT assignments_table_type_check CHECK (((type)::text = ANY ((ARRAY['THEORY'::character varying, 'PRACTICE'::character varying, 'TEST'::character varying, 'PROJECT'::character varying])::text[])))
);

ALTER TABLE assignments_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME assignments_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE course_learning_points (
    "position" integer NOT NULL,
    course_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint,
    text character varying(1000) NOT NULL
);

ALTER TABLE course_learning_points ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME course_learning_points_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE course_requirements (
     "position" integer NOT NULL,
     course_id bigint NOT NULL,
     created_at timestamp(6) without time zone NOT NULL,
     id bigint NOT NULL,
     updated_at timestamp(6) without time zone,
     version bigint,
     text character varying(1000) NOT NULL
);

ALTER TABLE course_requirements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME course_requirements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE courses (
    deleted boolean NOT NULL,
    duration_in_minutes integer,
    is_free boolean NOT NULL,
    price numeric(38,2) NOT NULL,
    rating double precision,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    reviews_count bigint,
    student_count bigint NOT NULL,
    teacher_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    version bigint,
    short_description character varying(400) NOT NULL,
    description character varying(2000) NOT NULL,
    level character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    preview_video_url character varying(255),
    status character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    type character varying(255) NOT NULL,
    CONSTRAINT courses_level_check CHECK (((level)::text = ANY ((ARRAY['BEGINNER'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying])::text[]))),
    CONSTRAINT courses_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT courses_type_check CHECK (((type)::text = ANY ((ARRAY['FREE'::character varying, 'PAID'::character varying])::text[])))
);

ALTER TABLE courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE enrollment_table (
    course_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    status character varying(255),
    CONSTRAINT enrollment_table_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_ACTIVE'::character varying, 'ACTIVE'::character varying, 'COMPLETED'::character varying, 'DROPPED'::character varying])::text[])))
);

ALTER TABLE enrollment_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME enrollment_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE lesson_content (
    "position" integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    lesson_id bigint,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255),
    thumbnail_url character varying(255),
    type character varying(255),
    url character varying(255),
    CONSTRAINT lesson_content_type_check CHECK (((type)::text = ANY ((ARRAY['PDF'::character varying, 'DOCX'::character varying, 'TXT'::character varying, 'RTF'::character varying, 'XLSX'::character varying, 'CSV'::character varying, 'PPTX'::character varying, 'PNG'::character varying, 'JPG'::character varying, 'JPEG'::character varying, 'SVG'::character varying, 'GIF'::character varying, 'MP4'::character varying, 'WEBM'::character varying, 'MOV'::character varying, 'AVI'::character varying, 'MP3'::character varying, 'WAV'::character varying, 'OGG'::character varying, 'JAVA'::character varying, 'PY'::character varying, 'JS'::character varying, 'HTML'::character varying, 'CSS'::character varying, 'SQL'::character varying, 'ZIP'::character varying, 'RAR'::character varying, 'TAR'::character varying, 'GZ'::character varying, 'JSON'::character varying, 'XML'::character varying, 'MD'::character varying, 'EPUB'::character varying])::text[])))
);

ALTER TABLE lesson_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lesson_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE lessons (
    duration integer,
    "position" integer,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    module_id bigint,
    updated_at timestamp(6) without time zone,
    name character varying(150),
    description character varying(1000),
    status character varying(255),
    CONSTRAINT lessons_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying, 'LOCKED'::character varying])::text[])))
);

ALTER TABLE lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE module_resource (
    "position" integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    module_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(150) NOT NULL,
    thumbnail_url character varying(500),
    url character varying(500) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT module_resource_type_check CHECK (((type)::text = ANY ((ARRAY['PDF'::character varying, 'DOCX'::character varying, 'TXT'::character varying, 'RTF'::character varying, 'XLSX'::character varying, 'CSV'::character varying, 'PPTX'::character varying, 'PNG'::character varying, 'JPG'::character varying, 'JPEG'::character varying, 'SVG'::character varying, 'GIF'::character varying, 'MP4'::character varying, 'WEBM'::character varying, 'MOV'::character varying, 'AVI'::character varying, 'MP3'::character varying, 'WAV'::character varying, 'OGG'::character varying, 'JAVA'::character varying, 'PY'::character varying, 'JS'::character varying, 'HTML'::character varying, 'CSS'::character varying, 'SQL'::character varying, 'ZIP'::character varying, 'RAR'::character varying, 'TAR'::character varying, 'GZ'::character varying, 'JSON'::character varying, 'XML'::character varying, 'MD'::character varying, 'EPUB'::character varying])::text[])))
);

ALTER TABLE module_resource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME module_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE modules (
    deleted boolean NOT NULL,
    "position" integer,
    course_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(150) NOT NULL,
    description character varying(1000),
    status character varying(255),
    type character varying(255),
    CONSTRAINT modules_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying, 'IN_PROGRESS'::character varying])::text[]))),
    CONSTRAINT modules_type_check CHECK (((type)::text = ANY ((ARRAY['FREE'::character varying, 'PAID'::character varying])::text[])))
);

ALTER TABLE modules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME modules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE token_table (
    is_logged_out boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    access_token character varying(1000) NOT NULL,
    refresh_token character varying(1000) NOT NULL
);

ALTER TABLE token_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME token_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE users_table (
    enabled boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_table_role_check CHECK (((role)::text = ANY ((ARRAY['COMMON_USER'::character varying, 'STUDENT'::character varying, 'TEACHER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE users_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME users_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY achievement_table
    ADD CONSTRAINT achievement_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY assignments_table
    ADD CONSTRAINT assignments_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY course_learning_points
    ADD CONSTRAINT course_learning_points_pkey PRIMARY KEY (id);

ALTER TABLE ONLY course_requirements
    ADD CONSTRAINT course_requirements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY enrollment_table
    ADD CONSTRAINT enrollment_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lesson_content
    ADD CONSTRAINT lesson_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY lessons
    ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);

ALTER TABLE ONLY module_resource
    ADD CONSTRAINT module_resource_pkey PRIMARY KEY (id);

ALTER TABLE ONLY modules
    ADD CONSTRAINT modules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY token_table
    ADD CONSTRAINT token_table_access_token_key UNIQUE (access_token);

ALTER TABLE ONLY token_table
    ADD CONSTRAINT token_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY token_table
    ADD CONSTRAINT token_table_refresh_token_key UNIQUE (refresh_token);

ALTER TABLE ONLY course_learning_points
    ADD CONSTRAINT uk_lp_position_course_id UNIQUE (course_id, "position");

ALTER TABLE ONLY course_learning_points
    ADD CONSTRAINT uk_lp_text_course_id UNIQUE (course_id, text);

ALTER TABLE ONLY modules
    ADD CONSTRAINT uk_module_name_courseid UNIQUE (name, course_id);

ALTER TABLE ONLY courses
    ADD CONSTRAINT uk_name UNIQUE (name);

ALTER TABLE ONLY lesson_content
    ADD CONSTRAINT uk_name_lesson_id UNIQUE (name, lesson_id);

ALTER TABLE ONLY module_resource
    ADD CONSTRAINT uk_name_moduleid UNIQUE (name, module_id);

ALTER TABLE ONLY modules
    ADD CONSTRAINT uk_position_courseid UNIQUE ("position", course_id);

ALTER TABLE ONLY lesson_content
    ADD CONSTRAINT uk_position_lesson_id UNIQUE ("position", lesson_id);

ALTER TABLE ONLY module_resource
    ADD CONSTRAINT uk_position_moduleid UNIQUE ("position", module_id);

ALTER TABLE ONLY course_requirements
    ADD CONSTRAINT uk_req_position_course_id UNIQUE (course_id, "position");

ALTER TABLE ONLY course_requirements
    ADD CONSTRAINT uk_req_text_course_id UNIQUE (course_id, text);

ALTER TABLE ONLY users_table
    ADD CONSTRAINT users_table_email_key UNIQUE (email);

ALTER TABLE ONLY users_table
    ADD CONSTRAINT users_table_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users_table
    ADD CONSTRAINT users_table_username_key UNIQUE (username);

CREATE INDEX idx_course_deleted ON courses USING btree (deleted);

CREATE INDEX idx_course_status ON courses USING btree (status);

CREATE INDEX idx_lesson_id ON lesson_content USING btree (lesson_id);

CREATE INDEX idx_module_id ON module_resource USING btree (module_id);

CREATE INDEX idx_teacher_id ON courses USING btree (teacher_id);

ALTER TABLE ONLY token_table
    ADD CONSTRAINT fkmqrvyvy4srny8fnty3drtb13n FOREIGN KEY (user_id) REFERENCES users_table(id);

